#!/usr/bin/env bash

if
  [[ -s "/Users/elliot/.rvm/gems/ruby-2.1.1/environment" ]]
then
  source "/Users/elliot/.rvm/gems/ruby-2.1.1/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/elliot/.rvm/gems/ruby-2.1.1/environment'" >&2
  exit 1
fi
