#!/usr/bin/env bash

if
  [[ -s "/Users/elliot/.rvm/gems/ruby-2.2.2@myapp/environment" ]]
then
  source "/Users/elliot/.rvm/gems/ruby-2.2.2@myapp/environment"
  exec sprockets "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/elliot/.rvm/gems/ruby-2.2.2@myapp/environment'" >&2
  exit 1
fi
