#!/usr/bin/env bash

if
  [[ -s "/Users/elliot/.rvm/gems/ruby-2.1.10/environment" ]]
then
  source "/Users/elliot/.rvm/gems/ruby-2.1.10/environment"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/elliot/.rvm/gems/ruby-2.1.10/environment'" >&2
  exit 1
fi
